## importando bibliotecas

In [2]:
import importlib
import pandas as pd

import template_credit_data

importlib.reload(template_credit_data)
from template_credit_data import templateCreditaData

## Lendo dataFrame

In [5]:
credits_tamplate = templateCreditaData()
base = credits_tamplate.base  # agora você acessa o DataFrame assim
base

      clientid        income        age         loan  default
0            1  66155.925095  59.017015  8106.532131        0
1            2  34415.153966  48.117153  6564.745018        0
2            3  57317.170063  63.108049  8020.953296        0
3            4  42709.534201  45.751972  6103.642260        0
4            5  66952.688845  18.584336  8770.099235        1
...        ...           ...        ...          ...      ...
1995      1996  59221.044874  48.518179  1926.729397        0
1996      1997  69516.127573  23.162104  3503.176156        0
1997      1998  44311.449262  28.017167  5522.786693        1
1998      1999  43756.056605  63.971796  1622.722598        0
1999      2000  69436.579552  56.152617  7378.833599        0

[2000 rows x 5 columns]

## Tratamento de valores inconsistente

In [3]:
base.loc[base['age'] < 0]

    clientid        income        age         loan  default
15        16  50501.726689 -28.218361  3977.287432        0
21        22  32197.620701 -52.423280  4244.057136        0
26        27  63287.038908 -36.496976  9595.286289        0

In [4]:
base[base['age'] < 0]

    clientid        income        age         loan  default
15        16  50501.726689 -28.218361  3977.287432        0
21        22  32197.620701 -52.423280  4244.057136        0
26        27  63287.038908 -36.496976  9595.286289        0

In [5]:
## Apagando colunas com dados invalidos 
base.drop(columns=['age'],axis=1)

      clientid        income         loan  default
0            1  66155.925095  8106.532131        0
1            2  34415.153966  6564.745018        0
2            3  57317.170063  8020.953296        0
3            4  42709.534201  6103.642260        0
4            5  66952.688845  8770.099235        1
...        ...           ...          ...      ...
1995      1996  59221.044874  1926.729397        0
1996      1997  69516.127573  3503.176156        0
1997      1998  44311.449262  5522.786693        1
1998      1999  43756.056605  1622.722598        0
1999      2000  69436.579552  7378.833599        0

[2000 rows x 4 columns]

In [6]:
## Apagando as linhas do dado invalido.
base.drop(base[base.age < 0].index)

      clientid        income        age         loan  default
0            1  66155.925095  59.017015  8106.532131        0
1            2  34415.153966  48.117153  6564.745018        0
2            3  57317.170063  63.108049  8020.953296        0
3            4  42709.534201  45.751972  6103.642260        0
4            5  66952.688845  18.584336  8770.099235        1
...        ...           ...        ...          ...      ...
1995      1996  59221.044874  48.518179  1926.729397        0
1996      1997  69516.127573  23.162104  3503.176156        0
1997      1998  44311.449262  28.017167  5522.786693        1
1998      1999  43756.056605  63.971796  1622.722598        0
1999      2000  69436.579552  56.152617  7378.833599        0

[1997 rows x 5 columns]

In [7]:
base[base['age'] > 0]['age'].mean()
base.loc[base.age < 0,'age'] = 40.92
base

      clientid        income        age         loan  default
0            1  66155.925095  59.017015  8106.532131        0
1            2  34415.153966  48.117153  6564.745018        0
2            3  57317.170063  63.108049  8020.953296        0
3            4  42709.534201  45.751972  6103.642260        0
4            5  66952.688845  18.584336  8770.099235        1
...        ...           ...        ...          ...      ...
1995      1996  59221.044874  48.518179  1926.729397        0
1996      1997  69516.127573  23.162104  3503.176156        0
1997      1998  44311.449262  28.017167  5522.786693        1
1998      1999  43756.056605  63.971796  1622.722598        0
1999      2000  69436.579552  56.152617  7378.833599        0

[2000 rows x 5 columns]

## Tratamento de valores Faltantes

In [8]:
pd.isnull(base['age'])
base.loc[pd.isnull(base['age'])]

    clientid        income  age         loan  default
28        29  59417.805406  NaN  2082.625938        0
30        31  48528.852796  NaN  6155.784670        0
31        32  23526.302555  NaN  2862.010139        0

In [9]:
previsores = base.iloc[:, 1:4].values
previsores

array([[6.61559251e+04, 5.90170151e+01, 8.10653213e+03],
       [3.44151540e+04, 4.81171531e+01, 6.56474502e+03],
       [5.73171701e+04, 6.31080495e+01, 8.02095330e+03],
       ...,
       [4.43114493e+04, 2.80171669e+01, 5.52278669e+03],
       [4.37560566e+04, 6.39717958e+01, 1.62272260e+03],
       [6.94365796e+04, 5.61526170e+01, 7.37883360e+03]])

In [10]:
classe = base.iloc[:, 4].values
classe

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [ ]:
import numpy as np
from sklearn.impute import SimpleImputer 
-
## Definindo a estratégia de como será preenchido a coluna 
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
# Maneira separand o metódo de aplicação do fit e do fit_transform

## Treina (ou ajusta) o modelo aos dados
imputer = imputer.fit(previsores[:, 0:3])
## Aplicando o conhecimento do modelo aprendido no fit
previsores[:, 0:3] = imputer.transform(previsores[:, 0:3])

# # Maneira unificada
# previsores[:, 0:3] = imputer.fit_transform(previsores[:, 0:3])

## Escalonamento de atributos

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()   

previsores = scaler.fit_transform(previsores)
previsores

array([[ 1.45393393,  1.36538093,  1.20281942],
       [-0.76217555,  0.5426602 ,  0.69642695],
       [ 0.83682073,  1.67417189,  1.17471147],
       ...,
       [-0.07122592, -0.97448519,  0.35420081],
       [-0.11000289,  1.73936739, -0.92675625],
       [ 1.682986  ,  1.14917639,  0.96381038]])